// UI v3: grade selector + separated grade 4 and grade 5 mathematics routes.
(() => {
  const allSkills=()=>[...EDU_MATH.flat(4),...EDU_MATH.flat(5)];
  const skillMap=new Map(allSkills().map(x=>[x.id,x]));
  const progressOf=id=>getp('math',id);
  const difficultyOf=id=>{const p=progressOf(id),a=Number(p.attempts||0),m=Number(p.mastery||0),st=Number(p.streak||0);if(a<4||m<60)return 0;if(a<8||m<68)return 1;if(a<13||m<74)return 2;if(a<20||m<80)return 3;if(a<30||m<86)return 4;return st>=4?5:4};
  const dLabel=d=>['D0 · база','D1 · уверенный базовый','D2 · средний','D3 · выше среднего','D4 · высокий','D5 · олимпиадный'][d]||`D${d}`;
  const pctSkill=id=>{let p=progressOf(id);return p.attempts?Math.round(Number(p.mastery)||0):0};
  const sectionPct=(g,sec)=>Math.round(sec.skills.reduce((sum,x)=>sum+pctSkill(x.id),0)/Math.max(sec.skills.length,1));
  const gradePct=g=>{let arr=EDU_MATH.flat(g);return Math.round(arr.reduce((s,x)=>s+pctSkill(x.id),0)/Math.max(arr.length,1))};
  const attemptedCount=g=>EDU_MATH.flat(g).reduce((s,x)=>s+Number(progressOf(x.id).attempts||0),0);
  const currentSkillFromProfile=()=>skillMap.get(prof?.current_math_topic)||null;
  const saveGrade=g=>{loc.grade=Number(g);save()};
  function inject(){if(document.getElementById('math-v3-inline'))return;let st=document.createElement('style');st.id='math-v3-inline';st.textContent=`.grade-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.grade-card{padding:26px;min-height:260px;position:relative;overflow:hidden}.grade-card.g4{background:linear-gradient(145deg,#e9f8ff,#e5fff1)}.grade-card.g5{background:linear-gradient(145deg,#f2edff,#e8f2ff)}.grade-num{position:absolute;right:18px;bottom:-25px;font-size:180px;font-weight:950;opacity:.08}.grade-card h2{font-size:32px;margin:0 0 8px}.grade-card p{line-height:1.55;color:#526080}.grade-meta{display:flex;gap:12px;flex-wrap:wrap;margin:16px 0}.grade-chip{background:rgba(255,255,255,.72);padding:7px 10px;border-radius:999px;font-size:12px;font-weight:800}.section-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.sec-card{padding:16px;cursor:pointer;min-height:145px}.sec-card:hover{transform:translateY(-2px)}.sec-card h3{font-size:15px;margin:7px 0}.skill-list{display:grid;gap:8px;margin-top:14px}.skill-row{display:grid;grid-template-columns:34px 1fr 72px;gap:10px;align-items:center;padding:11px;border:1px solid #e3e9f4;border-radius:12px;cursor:pointer;background:#fff}.skill-row:hover{background:#f7faff}.skill-dot{width:30px;height:30px;border-radius:10px;background:#edf3ff;display:grid;place-items:center;font-size:11px;font-weight:900;color:#1769ff}.skill-row small{display:block;color:#75809a;margin-top:2px}.level-badge{font-size:10px;font-weight:900;text-align:center;padding:5px 6px;border-radius:999px;background:#f1f4f9;color:#526080}.course-tools{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}.micro-title{font-size:12px;color:#6e7894;text-transform:uppercase;letter-spacing:.05em}.mastery-strip{display:grid;grid-template-columns:repeat(6,1fr);gap:4px;margin-top:10px}.mastery-strip i{height:5px;border-radius:99px;background:#e6eaf2}.mastery-strip i.on{background:#1769ff}.answer-note{font-size:11px;color:#6e7894;margin-top:8px}.section-summary{padding:18px}.course-head-v3{display:flex;justify-content:space-between;gap:12px;align-items:flex-start;margin-bottom:14px}.breadcrumb{font-size:12px;color:#6d7894;margin-bottom:5px}.quick-continue{margin-top:12px}.btn.ghost{background:#f4f7fd;border-color:#e1e8f5}@media(max-width:1000px){.section-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:700px){.grade-grid,.section-grid{grid-template-columns:1fr}.grade-card{min-height:220px}.grade-card h2{font-size:27px}.skill-row{grid-template-columns:32px 1fr 62px}.course-head-v3{display:block}.course-tools{margin-top:10px}}`;document.head.appendChild(st)}
  shell=function(body,on='home'){inject();document.getElementById('auth').innerHTML='';document.getElementById('app').innerHTML=`<div class=shell><aside class=side><div class=logo><div class=mark>📘</div><span>Умный ученик</span></div>${[['home','⌂','Главная'],['grade4','4','4 класс'],['grade5','5','5 класс'],['progress','▥','Прогресс'],['parent','👤','Родителю']].map(x=>`<button class="nav ${on===x[0]?'on':''}" onclick="nav('${x[0]}')"><span>${x[1]}</span><span>${x[2]}</span></button>`).join('')}</aside><main class=main><div class=top><h2 style="margin:0">${on==='home'?'Математика':on==='grade4'?'Математика · 4 класс':on==='grade5'?'Математика · 5 класс':on==='progress'?'Мой прогресс':'Для родителя'}</h2><div class=pill>⭐ <b>${prof?.xp||0}</b> · ${prof?.nickname||''}</div></div>${body}</main></div>`};
  nav=function(v){if(v==='home')return home();if(v==='grade4')return gradeHome(4);if(v==='grade5')return gradeHome(5);if(v==='progress')return stats();if(v==='parent')return parentInfo()};
  home=function(){inject();const cur=currentSkillFromProfile();const cont=cur?`<div class=quick-continue><button class="btn blue" onclick="openMathSkill(${cur.grade},'${cur.id}')">Продолжить: ${cur.title} →</button></div>`:'';shell(`<section class=welcome><h1>Выбери класс</h1><p>Курсы 4 и 5 класса разделены. У каждого класса собственные темы, задания и прогресс. Сложность повышается автоматически от D0 до D5.</p>${cont}</section><div class=grade-grid style="margin-top:16px">${gradeCard(4,'Школа России · Моро',`13 разделов · ${EDU_MATH.flat(4).length} микронавыков`,'Нумерация, величины, письменные вычисления, движение, геометрия, таблицы и диаграммы')}${gradeCard(5,'Виленкин · Ткачёва','51 последовательная тема','Натуральные числа, вычисления, площади и объёмы, обыкновенные и десятичные дроби, углы')}</div>`,'home')};
  function gradeCard(g,source,meta,desc){let p=gradePct(g),cnt=attemptedCount(g);return `<section class="card grade-card g${g}"><div class=grade-num>${g}</div><span class=tag>${source}</span><h2>${g} класс</h2><p>${desc}</p><div class=grade-meta><span class=grade-chip>${meta}</span><span class=grade-chip>${cnt} попыток</span></div><div class=bar><i style="width:${p}%;background:${g===4?'#13a45a':'#6d40df'}"></i></div><div class=small style="margin:6px 0 14px">Освоение курса: ${p}%</div><button class="btn ${g===4?'green':'purple'}" onclick="gradeHome(${g})">Открыть ${g} класс →</button></section>`}
  gradeHome=function(g){saveGrade(g);let sections=EDU_MATH.byGrade[g];shell(`<div class=course-head-v3><div><div class=breadcrumb>Математика → ${g} класс</div><h1 style="margin:0">Учебный маршрут</h1><p class=small>${g===4?'13 разделов S00–S12. Внутри каждого раздела — отдельные микронавыки.':'51 тема в последовательности учебника Виленкина и рабочей тетради Ткачёвой.'}</p></div><button class="btn blue" onclick="startGradePractice(${g})">Адаптивная тренировка</button></div><div class=section-grid>${sections.map(sec=>sectionCard(g,sec)).join('')}</div>`,g===4?'grade4':'grade5')};
  function sectionCard(g,sec){let p=sectionPct(g,sec),attempts=sec.skills.reduce((s,x)=>s+Number(progressOf(x.id).attempts||0),0);return `<section class="card sec-card" onclick="openMathSection(${g},'${sec.id}')"><span class=tag>${sec.skills.length} ${g===4?'микронавыков':'тем'}</span><h3>${sec.title}</h3><div class=small>${sec.desc}</div><div class=bar style="margin-top:12px"><i style="width:${p}%;background:${g===4?'#13a45a':'#6d40df'}"></i></div><div class=small style="margin-top:5px">${p}% · ${attempts} попыток</div></section>`}
  openMathSection=function(g,sectionId){saveGrade(g);let sec=EDU_MATH.findSection(g,sectionId)||EDU_MATH.byGrade[g][0];loc['section'+g]=sec.id;save();shell(`<div class=course-head-v3><div><div class=breadcrumb><a href="#" onclick="gradeHome(${g});return false">${g} класс</a> → ${sec.title}</div><h1 style="margin:0">${sec.title}</h1><p class=small>${sec.desc}</p></div><div class=course-tools><button class="btn blue" onclick="startSectionPractice(${g},'${sec.id}')">Начать раздел</button><button class="btn ghost" onclick="gradeHome(${g})">Все разделы</button></div></div><section class="card section-summary"><div class=small>Освоение раздела</div><div style="font-size:28px;font-weight:900">${sectionPct(g,sec)}%</div><div class=bar><i style="width:${sectionPct(g,sec)}%;background:#1769ff"></i></div></section><div class=skill-list>${sec.skills.map((sk,i)=>skillRow(g,sk,i)).join('')}</div>`,g===4?'grade4':'grade5')};
  function skillRow(g,sk,i){let p=progressOf(sk.id),d=difficultyOf(sk.id);return `<div class=skill-row onclick="openMathSkill(${g},'${sk.id}')"><div class=skill-dot>${i+1}</div><div><b>${sk.title}</b><small>${p.attempts?`${Math.round(Number(p.mastery))}% · ${p.attempts} попыток`:'ещё не начато'}</small></div><div class=level-badge>D${d}</div></div>`}
  openMathSkill=function(g,skillId){saveGrade(g);let sk=EDU_MATH.findSkill(g,skillId);if(!sk)return gradeHome(g);let sec=EDU_MATH.findSection(g,sk.sectionId);loc['section'+g]=sec.id;loc['skill'+g]=skillId;save();rpc('edu_set_current_topic',{p_student_token:loc.token,p_subject:'math',p_topic_id:skillId}).catch(()=>{});if(prof)prof.current_math_topic=skillId;renderSkillLesson(g,sk,sec)};
  function renderSkillLesson(g,sk,sec){let d=difficultyOf(sk.id),p=progressOf(sk.id);shell(`<div class=course-head-v3><div><div class=breadcrumb><a href="#" onclick="gradeHome(${g});return false">${g} класс</a> → <a href="#" onclick="openMathSection(${g},'${sec.id}');return false">${sec.title}</a></div><div class=micro-title>${g===4?'Микронавык':'Учебная тема'}</div><h1 style="margin:3px 0 6px">${sk.title}</h1>${sk.desc?`<p class=small>${sk.desc}</p>`:''}</div><button class="btn ghost" onclick="openMathSection(${g},'${sec.id}')">К разделу</button></div><section class="card lesson"><div class=theory><div class=tb><b>Текущая сложность</b><br>${dLabel(d)}. Выбирать уровень вручную не нужно.</div><div class=tb><b>Как растёт сложность</b><br>D0–D1: алгоритм; D2–D3: несколько шагов; D4: выбор стратегии; D5: нестандартная задача.</div></div><div class=mastery-strip>${[0,1,2,3,4,5].map(x=>`<i class="${x<=d?'on':''}"></i>`).join('')}</div><div class=small style="margin-top:5px">Освоение: ${p.attempts?Math.round(Number(p.mastery))+'%':'нет данных'} · серия: ${p.streak||0}</div><div id=mathTaskHost></div></section>`,g===4?'grade4':'grade5');nextMathTask(g,sk.id)}
  nextMathTask=function(g,skillId){let sk=EDU_MATH.findSkill(g,skillId);if(!sk)return;let d=difficultyOf(skillId),p=progressOf(skillId);window.__mathV3Task=EDU_GEN.make(sk.kind,d,Number(p.attempts||0));window.__mathV3Task.meta={grade:g,skillId,level:d};window.__mathV3Started=Date.now();let host=document.getElementById('mathTaskHost');if(!host)return;host.innerHTML=`<div class=task><div class=small>${sk.title} · ${dLabel(d)}</div><div class=q>${window.__mathV3Task.q}</div><div class=row><input id=mathAnswer placeholder="Введите ответ" autocomplete=off onkeydown="if(event.key==='Enter')checkMathTask()"><button class="btn blue" onclick=checkMathTask()>Проверить</button></div><div class=answer-note>Для дробей используй запись 3/5; десятичные числа можно вводить через запятую или точку.</div><div class=row style="margin-top:9px"><button class=btn onclick=showMathHint()>Подсказка</button><button class=btn onclick="nextMathTask(${g},'${skillId}')">Другое задание</button></div><div id=mathHint class=hint></div><div id=mathFeedback class=fb></div></div>`;document.getElementById('mathAnswer')?.focus()};
  function normalized(v){return String(v).trim().toLowerCase().replaceAll('ё','е').replace(/\s+/g,' ')} function parseFrac(v){let m=String(v).replace(',','.').trim().match(/^(-?\d+)\s*\/\s*(-?\d+)$/);if(!m||+m[2]===0)return null;return +m[1]/+m[2]}
  mathAnswerOk=function(value,t){let v=normalized(value),a=normalized(t.a);if(t.kind==='txt')return v===a;if(t.kind==='fr'){let x=parseFrac(v),y=parseFrac(a);return x!==null&&y!==null&&Math.abs(x-y)<1e-9}let x=Number(v.replace(',','.').replace(/\s/g,'')),y=Number(a.replace(',','.').replace(/\s/g,''));return Number.isFinite(x)&&Number.isFinite(y)&&Math.abs(x-y)<1e-7};
  showMathHint=function(){let h=document.getElementById('mathHint');if(h){h.textContent=window.__mathV3Task.h;h.classList.add('show')}};
  checkMathTask=async function(){let input=document.getElementById('mathAnswer');if(!input||!input.value.trim())return;let t=window.__mathV3Task,good=mathAnswerOk(input.value,t),fb=document.getElementById('mathFeedback');fb.className='fb '+(good?'ok':'bad');fb.innerHTML=good?`Верно. ${t.e}`:`Неверно. Правильный ответ: <b>${t.a}</b>. ${t.e}`;input.disabled=true;try{let res=await rpc('edu_save_attempt',{p_student_token:loc.token,p_subject:'math',p_topic_id:t.meta.skillId,p_difficulty:t.meta.level,p_is_correct:good,p_elapsed_seconds:Math.round((Date.now()-window.__mathV3Started)/1000)});if(res.length){let x=res[0];prog[key('math',t.meta.skillId)]={attempts:x.attempts,correct:x.correct,mastery:x.mastery,streak:x.streak,best_difficulty:x.best_difficulty,last_practiced_at:new Date().toISOString()};prof.xp=x.xp}}catch(e){console.error(e)}fb.innerHTML+=`<br><button class="btn blue" style="margin-top:8px" onclick="nextMathTask(${t.meta.grade},'${t.meta.skillId}')">Следующее</button>`};
  function weakestSkill(g,sec=null){let arr=sec?sec.skills:EDU_MATH.flat(g);let unseen=arr.find(x=>!Number(progressOf(x.id).attempts||0));if(unseen)return unseen;return [...arr].sort((a,b)=>pctSkill(a.id)-pctSkill(b.id)||Number(progressOf(a.id).attempts)-Number(progressOf(b.id).attempts))[0]}
  startSectionPractice=function(g,sectionId){let sec=EDU_MATH.findSection(g,sectionId);let sk=weakestSkill(g,sec);openMathSkill(g,sk.id)};startGradePractice=function(g){let sk=weakestSkill(g);openMathSkill(g,sk.id)};
  stats=function(){let rows=[4,5].flatMap(g=>EDU_MATH.flat(g).map(sk=>({g,sk,p:progressOf(sk.id)}))).filter(x=>Number(x.p.attempts||0)>0).sort((a,b)=>Number(a.p.mastery)-Number(b.p.mastery));shell(`<div class=kpis><div class="card kpi"><strong>${prof.xp}</strong><span class=small>баллов</span></div><div class="card kpi"><strong>${gradePct(4)}%</strong><span class=small>4 класс</span></div><div class="card kpi"><strong>${gradePct(5)}%</strong><span class=small>5 класс</span></div><div class="card kpi"><strong>${rows.reduce((s,x)=>s+Number(x.p.attempts||0),0)}</strong><span class=small>заданий</span></div></div><div class=card style="padding:16px;margin-top:14px;overflow:auto"><table class=table><thead><tr><th>Класс</th><th>Тема / микронавык</th><th>Попытки</th><th>Освоение</th><th>Уровень</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${x.g}</td><td>${x.sk.title}</td><td>${x.p.attempts}</td><td>${Math.round(Number(x.p.mastery))}%</td><td>D${difficultyOf(x.sk.id)}</td></tr>`).join('')||'<tr><td colspan=5>Пока нет выполненных заданий.</td></tr>'}</tbody></table></div>`,'progress')};
  parent=async function(){let el=document.getElementById('pc'),code=el?.value.trim();if(!code)return;try{let a=await rpc('edu_parent_profile',{p_parent_code:code});if(!a.length)return alert('Код не найден');let d=await rpc('edu_parent_progress',{p_parent_code:code});d=d.filter(z=>z.subject==='math');let p=a[0],tot=d.reduce((s,z)=>s+Number(z.attempts||0),0),cor=d.reduce((s,z)=>s+Number(z.correct||0),0);document.getElementById('auth').innerHTML='';document.getElementById('app').innerHTML=`<div class=main style="max-width:1150px;margin:auto"><div class=top><h2>Статистика: ${p.nickname}</h2><button class=btn onclick="location.reload()">Закрыть</button></div><div class=kpis><div class="card kpi"><strong>${p.xp}</strong><span class=small>баллов</span></div><div class="card kpi"><strong>${tot}</strong><span class=small>заданий</span></div><div class="card kpi"><strong>${tot?Math.round(cor/tot*100):0}%</strong><span class=small>точность</span></div><div class="card kpi"><strong>${p.last_activity?new Date(p.last_activity).toLocaleDateString('ru'):'—'}</strong><span class=small>последняя активность</span></div></div><div class=card style="padding:16px;margin-top:14px;overflow:auto"><table class=table><thead><tr><th>Класс</th><th>Тема</th><th>Попытки</th><th>Освоение</th><th>Макс. сложность</th></tr></thead><tbody>${d.map(z=>{let sk=skillMap.get(z.topic_id);let grade=sk?.grade||'—';return `<tr><td>${grade}</td><td>${sk?sk.title:z.topic_id}</td><td>${z.attempts}</td><td>${Math.round(Number(z.mastery))}%</td><td>D${z.best_difficulty}</td></tr>`}).join('')||'<tr><td colspan=5>Пока нет данных</td></tr>'}</tbody></table></div></div>`}catch(e){alert('Ошибка загрузки статистики')}};
  course=function(){gradeHome(Number(loc.grade)||4)};inject();
})();
