// Russian language UI v4: full grade 4 and 5 routes, matching mathematics architecture.
(() => {
  const rusSkills=()=>[...EDU_RUS.flat(4),...EDU_RUS.flat(5)];
  const rusMap=new Map(rusSkills().map(x=>[x.id,x]));
  const rp=id=>getp('russian',id);
  const rd=id=>{const p=rp(id),a=Number(p.attempts||0),m=Number(p.mastery||0),st=Number(p.streak||0);if(a<4||m<60)return 0;if(a<8||m<68)return 1;if(a<13||m<74)return 2;if(a<20||m<80)return 3;if(a<30||m<86)return 4;return st>=4?5:4};
  const dLabel=d=>['D0 · база','D1 · уверенный базовый','D2 · средний','D3 · выше среднего','D4 · высокий','D5 · олимпиадный'][d]||`D${d}`;
  const skillPct=id=>{let p=rp(id);return p.attempts?Math.round(Number(p.mastery)||0):0};
  const sectionPct=(g,sec)=>Math.round(sec.skills.reduce((s,x)=>s+skillPct(x.id),0)/Math.max(1,sec.skills.length));
  const gradePct=g=>Math.round(EDU_RUS.flat(g).reduce((s,x)=>s+skillPct(x.id),0)/Math.max(1,EDU_RUS.flat(g).length));
  const attempts=g=>EDU_RUS.flat(g).reduce((s,x)=>s+Number(rp(x.id).attempts||0),0);
  const saveRusGrade=g=>{loc.russianGrade=Number(g);save()};

  function inject(){if(document.getElementById('rus-v4-inline'))return;let st=document.createElement('style');st.id='rus-v4-inline';st.textContent=`
    .rus-section-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.rus-sec{padding:16px;cursor:pointer;min-height:145px}.rus-sec:hover{transform:translateY(-2px)}.rus-sec h3{font-size:15px;margin:7px 0}.rus-skill-list{display:grid;gap:8px;margin-top:14px}.rus-skill{display:grid;grid-template-columns:34px 1fr 72px;gap:10px;align-items:center;padding:11px;border:1px solid #e3e9f4;border-radius:12px;cursor:pointer;background:#fff}.rus-skill:hover{background:#fbf8ff}.rus-dot{width:30px;height:30px;border-radius:10px;background:#f1eaff;display:grid;place-items:center;font-size:11px;font-weight:900;color:#6d40df}.rus-level{font-size:10px;font-weight:900;text-align:center;padding:5px 6px;border-radius:999px;background:#f3effc;color:#6540bf}.rus-master{display:grid;grid-template-columns:repeat(6,1fr);gap:4px;margin-top:10px}.rus-master i{height:5px;border-radius:99px;background:#e6eaf2}.rus-master i.on{background:#6d40df}.rus-grade-card{background:linear-gradient(145deg,#f7edff,#eef1ff)}@media(max-width:1000px){.rus-section-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:700px){.rus-section-grid{grid-template-columns:1fr}.rus-skill{grid-template-columns:32px 1fr 62px}.subject-group.russian .nav.pending{opacity:1}}
  `;document.head.appendChild(st)}

  const baseShell=shell;
  shell=function(body,on='home'){baseShell(body,on);document.querySelectorAll('.subject-group.russian .nav.pending').forEach(x=>{x.classList.remove('pending');x.style.opacity='1'})};

  function rusGradeCard(g){let p=gradePct(g),cnt=attempts(g),meta=`${EDU_RUS.byGrade[g].length} разделов · ${EDU_RUS.flat(g).length} микронавыков`;return `<section class="card class-choice rus-grade-card"><div class=big-class>${g}</div><span class=tag>${g===4?'Школа России · Канакина, Горецкий':'Ладыженская · программа 5 класса'}</span><h2>${g} класс</h2><p class=small>${meta}</p><div class=bar><i style="width:${p}%;background:#6d40df"></i></div><div class=small style="margin:6px 0 14px">Освоение: ${p}% · ${cnt} попыток</div><button class="btn purple" onclick="showRussianGrade(${g})">Открыть курс →</button></section>`}

  const oldSubjectHome=window.subjectHome;
  window.subjectHome=function(subject){
    if(subject!=='russian')return oldSubjectHome(subject);
    shell(`<div class=course-head-v3><div><div class=breadcrumb>Русский язык</div><h1 style="margin:0">Выбери класс</h1><p class=small>Программы 4 и 5 класса разделены. Каждый курс содержит собственные разделы, микронавыки, адаптивные задания и прогресс.</p></div></div><div class=class-choice-grid>${rusGradeCard(4)}${rusGradeCard(5)}</div>`,'russian');
  };

  window.showRussianGrade=function(g){saveRusGrade(g);let sections=EDU_RUS.byGrade[g];shell(`<div class=course-head-v3><div><div class=breadcrumb>Русский язык → ${g} класс</div><h1 style="margin:0">Учебный маршрут</h1><p class=small>${sections.length} разделов. Внутри разделов — отдельные отслеживаемые микронавыки с автоматической сложностью D0–D5.</p></div><button class="btn purple" onclick="startRussianGradePractice(${g})">Адаптивная тренировка</button></div><div class=rus-section-grid>${sections.map(sec=>rusSectionCard(g,sec)).join('')}</div>`,`russian${g}`)};
  function rusSectionCard(g,sec){let p=sectionPct(g,sec),cnt=sec.skills.reduce((s,x)=>s+Number(rp(x.id).attempts||0),0);return `<section class="card rus-sec" onclick="openRussianSection(${g},'${sec.id}')"><span class=tag>${sec.skills.length} микронавыков</span><h3>${sec.title}</h3><div class=small>${sec.desc}</div><div class=bar style="margin-top:12px"><i style="width:${p}%;background:#6d40df"></i></div><div class=small style="margin-top:5px">${p}% · ${cnt} попыток</div></section>`}

  window.openRussianSection=function(g,sectionId){saveRusGrade(g);let sec=EDU_RUS.findSection(g,sectionId)||EDU_RUS.byGrade[g][0];loc['rusSection'+g]=sec.id;save();shell(`<div class=course-head-v3><div><div class=breadcrumb><a href="#" onclick="showRussianGrade(${g});return false">Русский язык · ${g} класс</a> → ${sec.title}</div><h1 style="margin:0">${sec.title}</h1><p class=small>${sec.desc}</p></div><div class=course-tools><button class="btn purple" onclick="startRussianSectionPractice(${g},'${sec.id}')">Начать раздел</button><button class="btn ghost" onclick="showRussianGrade(${g})">Все разделы</button></div></div><section class="card section-summary"><div class=small>Освоение раздела</div><div style="font-size:28px;font-weight:900">${sectionPct(g,sec)}%</div><div class=bar><i style="width:${sectionPct(g,sec)}%;background:#6d40df"></i></div></section><div class=rus-skill-list>${sec.skills.map((sk,i)=>rusSkillRow(g,sk,i)).join('')}</div>`,`russian${g}`)};
  function rusSkillRow(g,sk,i){let p=rp(sk.id),d=rd(sk.id);return `<div class=rus-skill onclick="openRussianSkill(${g},'${sk.id}')"><div class=rus-dot>${i+1}</div><div><b>${sk.title}</b><small>${p.attempts?`${Math.round(Number(p.mastery))}% · ${p.attempts} попыток`:'ещё не начато'}</small></div><div class=rus-level>D${d}</div></div>`}

  window.openRussianSkill=function(g,skillId){saveRusGrade(g);let sk=EDU_RUS.findSkill(g,skillId);if(!sk)return showRussianGrade(g);let sec=EDU_RUS.findSection(g,sk.sectionId);loc['rusSection'+g]=sec.id;loc['rusSkill'+g]=skillId;save();rpc('edu_set_current_topic',{p_student_token:loc.token,p_subject:'russian',p_topic_id:skillId}).catch(()=>{});if(prof)prof.current_russian_topic=skillId;renderRusLesson(g,sk,sec)};
  function renderRusLesson(g,sk,sec){let d=rd(sk.id),p=rp(sk.id);shell(`<div class=course-head-v3><div><div class=breadcrumb><a href="#" onclick="showRussianGrade(${g});return false">Русский язык · ${g} класс</a> → <a href="#" onclick="openRussianSection(${g},'${sec.id}');return false">${sec.title}</a></div><div class=micro-title>Микронавык</div><h1 style="margin:3px 0 6px">${sk.title}</h1>${sk.desc?`<p class=small>${sk.desc}</p>`:''}</div><button class="btn ghost" onclick="openRussianSection(${g},'${sec.id}')">К разделу</button></div><section class="card lesson"><div class=theory><div class=tb><b>Текущая сложность</b><br>${dLabel(d)}. Уровень определяется автоматически.</div><div class=tb><b>Нарастание сложности</b><br>D0–D1: распознавание правила; D2–D3: применение в слове и контексте; D4–D5: редактирование, смешанные и нестандартные случаи.</div></div><div class=rus-master>${[0,1,2,3,4,5].map(x=>`<i class="${x<=d?'on':''}"></i>`).join('')}</div><div class=small style="margin-top:5px">Освоение: ${p.attempts?Math.round(Number(p.mastery))+'%':'нет данных'} · серия: ${p.streak||0}</div><div id=rusTaskHost></div></section>`,`russian${g}`);nextRussianTask(g,sk.id)}

  window.nextRussianTask=function(g,skillId){let sk=EDU_RUS.findSkill(g,skillId);if(!sk)return;let d=rd(skillId),p=rp(skillId);window.__rusTask=EDU_RUS_GEN.make(sk.kind,d,Number(p.attempts||0));window.__rusTask.meta={grade:g,skillId,level:d};window.__rusStarted=Date.now();let host=document.getElementById('rusTaskHost');if(!host)return;host.innerHTML=`<div class=task><div class=small>${sk.title} · ${dLabel(d)}</div><div class=q>${window.__rusTask.q}</div><div class=row><input id=rusAnswer placeholder="Введите ответ" autocomplete=off onkeydown="if(event.key==='Enter')checkRussianTask()"><button class="btn purple" onclick=checkRussianTask()>Проверить</button></div><div class=answer-note>Регистр букв не учитывается. Ё и Е при проверке текстовых ответов считаются эквивалентными, если само задание не требует вставить конкретную букву.</div><div class=row style="margin-top:9px"><button class=btn onclick=showRussianHint()>Подсказка</button><button class=btn onclick="nextRussianTask(${g},'${skillId}')">Другое задание</button></div><div id=rusHint class=hint></div><div id=rusFeedback class=fb></div></div>`;document.getElementById('rusAnswer')?.focus()};
  const norm=v=>String(v).trim().toLowerCase().replace(/\s+/g,' ').replace(/[–—]/g,'-');
  function rusOk(v,t){let a=norm(t.a),x=norm(v);if(t.kind==='n'){let nx=Number(x.replace(',','.')),na=Number(a.replace(',','.'));return Number.isFinite(nx)&&Number.isFinite(na)&&Math.abs(nx-na)<1e-9}if(['ё','е'].includes(a)&&['ё','е'].includes(x)&&t.q.includes('О или Ё'))return x===a;return x.replaceAll('ё','е')===a.replaceAll('ё','е')}
  window.showRussianHint=function(){let h=document.getElementById('rusHint');if(h){h.textContent=window.__rusTask.h;h.classList.add('show')}};
  window.checkRussianTask=async function(){let input=document.getElementById('rusAnswer');if(!input||!input.value.trim())return;let t=window.__rusTask,good=rusOk(input.value,t),fb=document.getElementById('rusFeedback');fb.className='fb '+(good?'ok':'bad');fb.innerHTML=good?`Верно. ${t.e}`:`Неверно. Правильный ответ: <b>${t.a}</b>. ${t.e}`;input.disabled=true;try{let res=await rpc('edu_save_attempt',{p_student_token:loc.token,p_subject:'russian',p_topic_id:t.meta.skillId,p_difficulty:t.meta.level,p_is_correct:good,p_elapsed_seconds:Math.round((Date.now()-window.__rusStarted)/1000)});if(res.length){let x=res[0];prog[key('russian',t.meta.skillId)]={attempts:x.attempts,correct:x.correct,mastery:x.mastery,streak:x.streak,best_difficulty:x.best_difficulty,last_practiced_at:new Date().toISOString()};prof.xp=x.xp}}catch(e){console.error(e)}fb.innerHTML+=`<br><button class="btn purple" style="margin-top:8px" onclick="nextRussianTask(${t.meta.grade},'${t.meta.skillId}')">Следующее</button>`};

  function weakest(g,sec=null){let arr=sec?sec.skills:EDU_RUS.flat(g),unseen=arr.find(x=>!Number(rp(x.id).attempts||0));if(unseen)return unseen;return [...arr].sort((a,b)=>skillPct(a.id)-skillPct(b.id)||Number(rp(a.id).attempts)-Number(rp(b.id).attempts))[0]}
  window.startRussianSectionPractice=function(g,id){let sec=EDU_RUS.findSection(g,id),sk=weakest(g,sec);openRussianSkill(g,sk.id)};
  window.startRussianGradePractice=function(g){let sk=weakest(g);openRussianSkill(g,sk.id)};

  const mathGradePct=g=>{let arr=EDU_MATH.flat(g);return Math.round(arr.reduce((s,x)=>{let p=getp('math',x.id);return s+(p.attempts?Number(p.mastery)||0:0)},0)/Math.max(1,arr.length))};
  home=function(){inject();let cm=[...EDU_MATH.flat(4),...EDU_MATH.flat(5)].find(x=>x.id===prof?.current_math_topic),cr=rusMap.get(prof?.current_russian_topic);let cont=[cm?`<button class="btn green" onclick="openMathSkill(${cm.grade},'${cm.id}')">Продолжить математику →</button>`:'',cr?`<button class="btn purple" onclick="openRussianSkill(${cr.grade},'${cr.id}')">Продолжить русский язык →</button>`:''].filter(Boolean).join(' ');shell(`<section class=welcome><h1>Выбери предмет</h1><p>Математика и русский язык разделены по 4 и 5 классам. В каждом курсе — отдельные разделы, микронавыки, адаптивная сложность и синхронизированный прогресс.</p>${cont?`<div class=quick-continue>${cont}</div>`:''}</section><div class=subject-landing style="margin-top:16px"><section class="card subject-card-v4 math"><div class=subject-symbol>∑</div><span class=tag>4 и 5 классы</span><h2>Математика</h2><p>Раздельные маршруты 4 и 5 класса с генеративными заданиями.</p><button class="btn green" onclick="subjectHome('math')">Выбрать класс →</button></section><section class="card subject-card-v4 russian"><div class=subject-symbol>Я</div><span class=tag>4 и 5 классы</span><h2>Русский язык</h2><p>Орфография, грамматика, синтаксис, лексика, фонетика и работа с текстом.</p><button class="btn purple" onclick="subjectHome('russian')">Выбрать класс →</button></section></div>`,'home')};

  stats=function(){let mathRows=[4,5].flatMap(g=>EDU_MATH.flat(g).map(sk=>({subject:'Математика',g,sk,p:getp('math',sk.id),d:(()=>{let p=getp('math',sk.id),a=+p.attempts||0,m=+p.mastery||0,st=+p.streak||0;return a<4||m<60?0:a<8||m<68?1:a<13||m<74?2:a<20||m<80?3:a<30||m<86?4:st>=4?5:4})()}))),rusRows=[4,5].flatMap(g=>EDU_RUS.flat(g).map(sk=>({subject:'Русский язык',g,sk,p:rp(sk.id),d:rd(sk.id)}))),rows=[...mathRows,...rusRows].filter(x=>Number(x.p.attempts||0)>0).sort((a,b)=>Number(a.p.mastery)-Number(b.p.mastery));let total=rows.reduce((s,x)=>s+Number(x.p.attempts||0),0);shell(`<div class=kpis style="grid-template-columns:repeat(3,1fr)"><div class="card kpi"><strong>${prof.xp}</strong><span class=small>баллов</span></div><div class="card kpi"><strong>${mathGradePct(4)}% / ${mathGradePct(5)}%</strong><span class=small>математика · 4 / 5</span></div><div class="card kpi"><strong>${gradePct(4)}% / ${gradePct(5)}%</strong><span class=small>русский · 4 / 5</span></div><div class="card kpi"><strong>${total}</strong><span class=small>всего заданий</span></div></div><div class=card style="padding:16px;margin-top:14px;overflow:auto"><table class=table><thead><tr><th>Предмет</th><th>Класс</th><th>Тема</th><th>Попытки</th><th>Освоение</th><th>Уровень</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${x.subject}</td><td>${x.g}</td><td>${x.sk.title}</td><td>${x.p.attempts}</td><td>${Math.round(Number(x.p.mastery))}%</td><td>D${x.d}</td></tr>`).join('')||'<tr><td colspan=6>Пока нет выполненных заданий.</td></tr>'}</tbody></table></div>`,'progress')};

  parent=async function(){let el=document.getElementById('pc'),code=el?.value.trim();if(!code)return;try{let a=await rpc('edu_parent_profile',{p_parent_code:code});if(!a.length)return alert('Код не найден');let d=await rpc('edu_parent_progress',{p_parent_code:code}),p=a[0],mathMap=new Map([...EDU_MATH.flat(4),...EDU_MATH.flat(5)].map(x=>[x.id,x])),tot=d.reduce((s,z)=>s+Number(z.attempts||0),0),cor=d.reduce((s,z)=>s+Number(z.correct||0),0);document.getElementById('auth').innerHTML='';document.getElementById('app').innerHTML=`<div class=main style="max-width:1200px;margin:auto"><div class=top><h2>Статистика: ${p.nickname}</h2><button class=btn onclick="location.reload()">Закрыть</button></div><div class=kpis><div class="card kpi"><strong>${p.xp}</strong><span class=small>баллов</span></div><div class="card kpi"><strong>${tot}</strong><span class=small>заданий</span></div><div class="card kpi"><strong>${tot?Math.round(cor/tot*100):0}%</strong><span class=small>точность</span></div><div class="card kpi"><strong>${p.last_activity?new Date(p.last_activity).toLocaleDateString('ru'):'—'}</strong><span class=small>последняя активность</span></div></div><div class=card style="padding:16px;margin-top:14px;overflow:auto"><table class=table><thead><tr><th>Предмет</th><th>Класс</th><th>Тема</th><th>Попытки</th><th>Освоение</th><th>Макс. сложность</th></tr></thead><tbody>${d.map(z=>{let sk=z.subject==='russian'?rusMap.get(z.topic_id):mathMap.get(z.topic_id);return `<tr><td>${z.subject==='russian'?'Русский язык':'Математика'}</td><td>${sk?.grade||'—'}</td><td>${sk?sk.title:z.topic_id}</td><td>${z.attempts}</td><td>${Math.round(Number(z.mastery))}%</td><td>D${z.best_difficulty}</td></tr>`}).join('')||'<tr><td colspan=6>Пока нет данных</td></tr>'}</tbody></table></div></div>`}catch(e){alert('Ошибка загрузки статистики')}};

  inject();
})();
